POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Video node",
  "description": "Video 1 description",
  "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/a9d672c4-5cbf-4bd7-8799-26b9cb30f152
Content-Type: application/json

{
  "title": "Video node atualizado",
  "description": "Video 1 description",
  "duration": 280
}

###

DELETE http://localhost:3333/videos/a9d672c4-5cbf-4bd7-8799-26b9cb30f152
